[package]
name = "_2"
version = "0.1.0"
authors = ["myles <landais.myles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.1.0"
clap = "2.32.0"
failure = "0.1.5"
